import { SecurityContext } from "@webiny/api-security/types";
import { TenancyContext } from "@webiny/api-tenancy/types";
import { PbContext } from "@webiny/api-page-builder/types";
import { CmsContext, CmsEntry } from "@webiny/api-headless-cms/types";
import { GroupsContext } from "./websiteGroups/types";
import { UsersContext } from "./websiteUsers/types";

export interface WebsiteContext extends TenancyContext, SecurityContext, PbContext, CmsContext {
    websiteGroups: GroupsContext;
    websiteUsers: UsersContext;
}

export interface WebsiteSecurityConfig {
    region: string;
    userPoolId: string;
}

export interface ContentModule {
    // Headless CMS content model ID.
    contentModelId: string;
    // Page Builder page template slug. This template is used to generate static pages for the `contentModel` defined above.
    pageTemplateSlug: string;
    // A generator function for static page path, e.g.: `/articles/63f290cb4f84750008dc99b5`.
    articlePath: (entry: CmsEntry) => `/${string}`;
    // Tags to be assigned to every page generated by this module. Useful for page list filtering.
    pageTags: string[];
    // Module "homepage" which renders a dynamic list of pages.
    homepage?: `/${string}`;
    // Default pages to copy to each tenant on setup.
    defaultPages?: Array<`/${string}`>;
}
